title: Neosys blog
email: bbsaila@neosys.fr
github_username:  ns-bbsaila
description: Le journal technique de Neosys

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  authors:
    output: true

plugins:
  - jemoji
  - jekyll-gist
  

github:
  prs_link: https://github.com/neosys-opentech/blog/pulls
  issues_link: https://github.com/neosys-opentech/blog/issues

baseurl: /blog
